### ISSUE TITLE
Home page drop-downs

### ISSUE THREAD

**Issue by apdavison** [HumanBrainProject/hbp-validation-framework#126]
On the home page we should show the selections that have been made in the config view, so that people can see what this instance of the app is all about, e.g. "Showing single cell models, hippocampus, HBP-SP6"

Related to this, we should not show any drop-down list that contains only a single entry.

**Comment by appukuttan-shailesh** [comment]
Implemented in v2 apps already on top of page "View Current Configuration".
v1 apps will be dropped soon.
