### ISSUE TITLE
Properties like "cell_type" etc, have to be a foreign key pointing to "params" tables, instead of beeing a string in models.py

### ISSUE THREAD

**Issue by joffreygonin** [HumanBrainProject/hbp-validation-framework#140]
What does it involve ? When registering a new model for example, we will have to pass the id of such a parameter instead of the string... 

The python client will then receive a list of dictionary from "/authorizedcollabparameterrest/" instead of a list of strings. 

Previous use : 
self.url + "/authorizedcollabparameterrest/?python_client=true&parameters="+param+"&format=json"

Next : 
self.url + "/authorizedcollabparameterrest/?parameters="+param+"&format=json"

**Comment by apdavison** [comment]
No longer applies following migration to KG
