### ISSUE TITLE
Scores not placed correctly against test instance in results table

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#141]
The scores are currently not placed correctly against test instance in results table.
For e.g. 
![image](https://user-images.githubusercontent.com/24866517/35734421-60a97072-0821-11e8-8971-fda093ba5225.png)

Results for model versions `4.0` and '4.0a` were run for test instance `6.0`... but currently these are reflected under `1.0`. I have verified that the problem is not in how the data is registered in the database. Seems to be only an issue with the visualization.

**Comment by HFragnaud** [comment]
#145  should be fixed
