### ISSUE TITLE
png figures too big at the test-results tab  

### ISSUE THREAD

**Issue by pedroernesto** [HumanBrainProject/hbp-validation-framework#152]
I have this problem when using the 'Preview' option available for the test 'CA1 laminar-distribution-synapses Freeman-Tukey-2-Test':

https://collab.humanbrainproject.eu/#/collab/5165/nav/42859?state=result.38517108-87cf-44d8-813b-8902dba2ab2f
![capture du 2018-03-16 16-42-37](https://user-images.githubusercontent.com/23551025/37530108-26d6da90-2939-11e8-8c73-0541cd01db8d.png)

**Comment by appukuttan-shailesh** [comment]
Implemented in v2 apps already.
v1 apps will be dropped soon.
