### ISSUE TITLE
Loading models (and tests) page wise for faster loads

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#161]
Currently the model catalog tries to retrieve all the data from the database before displaying the contents in the app. This was ok initially when the entries were few, but now we have started seeing a notable lag. This was evident in the "dev" environment earlier, and now also on the "production" because of the recent growth in size.

@apdavison , @HFragnaud : I think we need to do the data loading page-wise, so that the users are shown the most recent (top 100?) info immediately. And in the meantime (in the background) we load the remaining data. We probably should take this up on priority. Also, it might be useful to have a "loading" message when there is significant delay. As of now, the user simply sees an empty Model Catalog, which could be misleading.

**Comment by apdavison** [comment]
I agree. I noticed a significant lag, especially on pages where there are few filters (and hence a lot of models).

**Comment by apdavison** [comment]
It should be quick and easy to add a "loading" message, the pagination will take more work.
