### ISSUE TITLE
Add `search_fields` on Django admin page

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#172]
Here in this file: https://github.com/HumanBrainProject/hbp-validation-framework/blob/ea0368c41c06fa81a9a1463dd5507a92902a077c/model_validation_api/admin.py

Similar to how `ValidationTestDefinitionAdmin` and `ValidationTestResultAdmin` have `search_fields` and `filters`, we should have the same for Models, Model Instances, Model Images etc.... this makes it easier for admins to find and delete unwanted entries. 

Also, it would be really useful if the UUIDs are included in the `search_fields` and `filters` for all the entities.

**Comment by appukuttan-shailesh** [comment]
@HFragnaud : I think this was partially implemented? It seems to throw errors when searching.
> TypeError at /admin/model_validation_api/scientificmodel/
Related Field got invalid lookup: icontains

**Comment by apdavison** [comment]
Django admin interface no longer useful since move to KG, will disappear entirely with v2.
