### ISSUE TITLE
Update PUT REST API to handle missing parameters

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#181]
PUT APIs (for all edits... models, model instances, model images, tests, test instance) currently require each parameter to be specified (even if they are not being updated). @apdavison proposed that we update this to have the API accept missing parameters in PUT requests, or to define PATCH endpoints.

Note: this is related to the python client fix [here](https://github.com/HumanBrainProject/hbp-validation-client/pull/17)

**Comment by apdavison** [comment]
Implemented in v2, using PUT (which behaves like PATCH).
