### ISSUE TITLE
Model catalog app not being configured on first attempt

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#187]
When a new Model Catalog app is created, we are automatically taken to the configuration page. After choosing the filters, there seems to be a problem in saving the settings. I tested this a few times, and each time I had to go out of the config page, and revisit it to save the settings.

**Comment by HFragnaud** [comment]
i don't see this behavior... do you still have this issue? maybe we should take a look together.

**Comment by appukuttan-shailesh** [comment]
As we saw now, problem only on Chrome.... not on Firefox.

**Comment by appukuttan-shailesh** [comment]
Has been implemented in Collab v2 web apps.
v1 apps will soon be dropped.
