### ISSUE TITLE
Display access permissions for models on model detailed view

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#192]
Partly related to #191 

As a user cannot edit/update all the models that they see in the model catalog, it would be useful to have icons (maybe inside a "Permissions" box?) that indicate whether a user has only READ permissions for that specific model, or both READ and WRITE.

Often it is not easy to identify why you don't see the "EDIT" options for some of the models. Also, you cannot run a test on any model that you see in the model catalog. You need to have WRITE permissions for these models.

For APIs,
READ = GET
WRITE = PUT/POST

@apdavison : Go ahead with this?

**Comment by apdavison** [comment]
Why do you need write permission to run a test on a model?

**Comment by appukuttan-shailesh** [comment]
To be more accurate... running the test does not require write, but to register the new results (POST) we require write permission.

**Comment by apdavison** [comment]
Why?

**Comment by appukuttan-shailesh** [comment]
If the model is `public` but the user is not a member of the model's host Collab. The user can see the model in the model catalog, but cannot PUT/POST.

See table here: http://hbp-validation-client.readthedocs.io/en/master/#general-info

**Comment by appukuttan-shailesh** [comment]
This is as per the current implementation. Found an example of this last week.

**Comment by apdavison** [comment]
No permissions should be required to post test results (the user just needs an HBP account).

If there are related data, then the user should specify a collab for which he/she has permission to write to the storage.

Even if writing to storage fails, however, the result should still be registered.

**Comment by apdavison** [comment]
On the topic of the issue, I agree it would be useful to display a small box that explains the permissions.

**Comment by appukuttan-shailesh** [comment]
This continues to be a problem... should we take this up on priority?
