### ISSUE TITLE
Add `morphology` field to model instance schema; implement in model catalog

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#223]
Add a new field named `morphology` to the model instance. This field can accept multiple URLs.
API should return this as a "list" of URLs.

@HFragnaud : setting as "priority" (even though not very important) as we have external help on this at the moment. So would be good to get this done soon, as it would help with testing and debugging.

**Comment by appukuttan-shailesh** [comment]
The model catalog also needs to be updated to accept the `morphology` parameter. If input, then we need to show a button "View Morphology" next to the model instance to launch the morphology in the morphology viewer.

**Comment by appukuttan-shailesh** [comment]
Sample URL to launch the morphology viewer:
`https://neuroinformatics.nl/HBP/morphology-viewer-dev/?hbp-model-instance-id=cc3effd5-cd9f-441f-b0bd-382300e5a578`
**Note:** the UUID corresponds to the model instance

**Comment by apdavison** [comment]
Why is a list of URLs needed?

**Comment by appukuttan-shailesh** [comment]
E.g. for network models where the model owner wishes to highlight sample morphologies of multiple cell types in the network

**Comment by appukuttan-shailesh** [comment]
Closing issue as no longer relevant.
