### ISSUE TITLE
Model Catalog database migration to KG 

### ISSUE THREAD

**Issue by HFragnaud** [HumanBrainProject/hbp-validation-framework#227]
### Makes schemas
- [x]  create ModelProject
- [x]  update ModelScript
- [x]  update TypeLabeledOntologyTerm
- [x]  update ModelInstance

### Update NAR client
- [x]  create ModelProject Object
- [x]  update Ontologies
- [x]  create ModelInstance Object 

### Update API 
    1. Update Models class
- [x]  get
- [x]  post
- [x]  put 
    2. Update AuthorizedCollabParameters class 
- [x]  get
    3. Update ModelInstances class
- [x]  get
- [x]  post
- [ ]  put
    3. Delete  Images class
- [x]  NB: images should all be included in ModelProject description. 
    4. Update ModelAlias class
- [ ] get
    5. Create a Person class
- [ ] get
- [ ] post
- [ ] put

### Update WebApp 
    1. Authors/Owners 
- [ ] Create a panel/page to enter a new Person 
- [ ] When creating a new model, add a list to retrieve persons for authors (owner should be automatically added)

**Comment by apdavison** [comment]
Done
