### ISSUE TITLE
Add "Launch in BlueNaaS" feature to model instances

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#228]
Similar to the "Morphology" field and "View Morphology" button, we need to add a button labeled "Launch in BlueNaaS" next to the "Download Location" for model versions. 

p.s. the scroll bar for "morphology" field doesn't display the entire contents... lets have this resolved for both
(e.g. https://collab.humanbrainproject.eu/#/collab/5165/nav/41550?state=model.3689543c-eb2c-4d76-806e-bda7a8e0b9eb)

**Comment by apdavison** [comment]
Looks good to me.

**Comment by appukuttan-shailesh** [comment]
@HFragnaud : Tested on dev. Works well :)

A few small things we need to look at:
1) Add a scroll bar for the 'Download Location' as this can be really long
2) The scroll bar for 'Morphology' field doesn't display the entire contents (also ensure we don't have this problem for 'Download Location' now)
3) Should we display 'Code Format' and 'Download Location' also with a box appearance?

**Comment by appukuttan-shailesh** [comment]
Implemented as proposed above.
