### ISSUE TITLE
REST API documentation needs to be updated

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#229]
REST API documentation does not seem to reflect the recent changes on VF.

https://hbp-validation-framework-api.readthedocs.io

**Comment by apdavison** [comment]
Probably not worth doing for v1. It's a shame, though, as the v1 documentation was very well done.

v2 documentation (to be improved with more descriptions) is auto-generated, available at https://validation-v2.brainsimulation.eu/docs

Leaving this ticket open until we're sure that all useful information from the v1 docs is available in the v2 docs.

**Comment by appukuttan-shailesh** [comment]
Closing issue as no longer relevant.

Relevant info from old docs retained in docs for Python client:
https://hbp-validation-client.readthedocs.io/en/master/
