### ISSUE TITLE
Result should have 'run time' and 'hash' field

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#230]
As part of each validation test result, we should also record the time required for running that test (as an optional parameter). Also, add a 'hash' field to identify duplicate test result entries. The following needs to be done:

1) Add field to database
2) Update REST APIs (GET, POST, PUT?) for this new field
3) Update GUI to show this 

Related to: https://github.com/HumanBrainProject/hbp-validation-client/issues/34

**Comment by appukuttan-shailesh** [comment]
@apdavison : should `hash` be enforced to be both **mandatory** and **unique**? Older entries would have this field empty, so not sure if we can enforce it to be mandatory.

**Comment by apdavison** [comment]
I don't think it should be mandatory. It should be safe to declare it unique (only if you had the same test running at the same time on different machines might you get duplicate values), but I'm not sure it's necessary, as it will not be used as a primary identifier.

**Comment by appukuttan-shailesh** [comment]
You are right. Infact the duplicates can technically only arise if these results (with same test, model and timestamp) are run on the same machine as we have a `platform` field in the results JSON storing machine info. And this scenario is quite unlikely (if not near impossible?).

The advantage of enforcing this (if I am correct) as 'unique' in the database schema would be being able to avoid manual checks for duplicate results on the python client or REST APIs.

I am in favor of having this field as optional but unique (i.e. blank or unique value).

**Comment by appukuttan-shailesh** [comment]
Implemented
