### ISSUE TITLE
Decide if model instances should have 'images' attribute

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#231]
Decide if model instances should have 'images' attribute
Also, if this should be moved away from the models (as currently) and only be associated with model instances.

Might be undertaken post KnowledgeGraph integration.

**Comment by apdavison** [comment]
With reference to #183, I guess the answer is no? Both models and model instances have their own "description" fields, which can contain Markdown.

**Comment by appukuttan-shailesh** [comment]
I agree in principle... except the case of images being removed/renamed/moved from the host server, and we having broken URLs for these images. If we could have these images stored on our server, we have more control over this.

**Comment by appukuttan-shailesh** [comment]
No longer relevant with new version of app and APIs.
