### ISSUE TITLE
Ability to retrieve multiple models/tests/results with one API call

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#243]
Currently all the `GET` API calls with specification of UUIDs permit only a single entry to be retrieved at a time. It would be useful to extend this to allow users to input a list of UUIDs and have all the data returned in a single go. This would avoid the need for multiple API calls and thereby make the workflow faster.

**Comment by apdavison** [comment]
I've implemented this on the server side for models, it will need a few changes in the client.

In `list_models()`, add "id" to `valid_filters` and then add `doseq=True` to the `urlencode()` call. The error handling might also need some updating - you can get an idea of the new return values (in case some of the IDs are invalid or unauthorised) here: https://github.com/apdavison/hbp-validation-framework/commit/0e42afa238e70d6994407d883b3319a7b6ed5fad


Still to do: model instances, tests, results

**Comment by apdavison** [comment]
From looking at the code (not tested), all the other resources (instances, tests, results) already support supplying multiple uuids

**Comment by appukuttan-shailesh** [comment]
Not sure if its implemented for other resources. Tested for tests now:
`testLibrary.list_tests(id=["44edca95-cc04-492d-8c60-49ad36cba123", "01c68387-fcc4-4fd3-85f0-6eb8ce4467a1"])`
and got:
> u'Badly formed uuid in : id'

The following worked for models:
`modelCatalog.list_models(model_id = ["0327c2ee-253a-420e-9f3e-e886d7faf3a6", "0154c5a8-05e4-4261-9ab3-d70d7faa10a3"])`

**Comment by apdavison** [comment]
It's implemented in the API, you'll need to update the client.

**Comment by appukuttan-shailesh** [comment]
You are right, I had updated the client but forgot to add `doseq=True` for these.

The difference seems to be that the models return output in the form of a dict with keys `models` and `errors`, the latter being sub-divided as `unauthorized` and `not found`. But tests and results, simply return the valid outputs, with no comment on the "errors". Do we change this to make all `list_*()` methods to be consistent?

**Comment by apdavison** [comment]
Yes, we should make them consistent
