### ISSUE TITLE
Broken links in web app pages

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#244]
The URL's to detailed results pages are broken!

e.g. 
https://collab.humanbrainproject.eu/#/collab/8123/nav/68490?state=model.21274988-13af-46b2-bbc6-9e15b26f3900

Click on any score, and the URL becomes:
https://collab.humanbrainproject.eu/#/collab/8123/nav/68490?state=result.%5Bobject%20Object%5D

@apdavison : do take a look if you find the same.

**Comment by appukuttan-shailesh** [comment]
Similarly,
On the test result page, e.g.
https://collab.humanbrainproject.eu/#/collab/8123/nav/68490?state=result.fb247d14-eab9-478b-87b3-0934cb871b8f

The link for "(more details on model catalog)" does not redirect properly.

**Comment by apdavison** [comment]
This has been fixed for the score links on the staging server. I haven't yet tested the "more details" links.

**Comment by appukuttan-shailesh** [comment]
Scores links now work.

For the "more details" links:

- (more details on model results page)
Page opens, but "results" not populated on this page.

- (more details on model catalog)
Fails... seems to open in an invalid model catalog instance.
e.g. for this result:
https://collab.humanbrainproject.eu/#/collab/8609/nav/407996?state=result.5e10ac38-f5ea-4a79-a219-dd6f48c765c3
it redirects me to:
https://collab.humanbrainproject.eu/#/collab/8609/nav/**68628**?state=model.2fc841a2-c5f8-4e47-900e-ff35dfdb7af4,external
whereas it should have actually taken me to 
https://collab.humanbrainproject.eu/#/collab/8609/nav/**407995**?state=model.2fc841a2-c5f8-4e47-900e-ff35dfdb7af4
i.e. NAV_ID should not be `68628` but rather `407995`

- (more details on test results page)
Works! .... just that results load a bit slow.

**Comment by apdavison** [comment]
The "opening in an invalid model catalog" issue is not a major one, since most people only have one instance of the app installed. We should fix this at some point, but it's a low priority.

**Comment by appukuttan-shailesh** [comment]
I think this was misunderstood...... it is currently redirecting to an invalid **broken** URL (with NAV_ID = 68628). An app with this ID does not exist in this Collab.

i.e. 
https://collab.humanbrainproject.eu/#/collab/8609/nav/68628?state=model.2fc841a2-c5f8-4e47-900e-ff35dfdb7af4,external
is invalid and broken

correct URL should have been corresponding to a model catalog instance in that Collab (in this case a single instance with NAV_ID = 407995):
https://collab.humanbrainproject.eu/#/collab/8609/nav/407995?state=model.2fc841a2-c5f8-4e47-900e-ff35dfdb7af4

**Comment by apdavison** [comment]
ok, I was confusing it with a related issue whereby it redirects to a valid Model Catalog app in the same collab, but not the appropriate one (e.g. staging redirecting to production).

**Comment by apdavison** [comment]
so it turns out that when apps are deleted from the collab, they are not deleted from the vf database, so you were being directed to an app instance that no longer exists in that collab. As a temporary workaround, I've deleted the invalid entries from the database, so it should work now. 

To fix this properly, we should change to querying the Collab service API instead of our database. Please leave this ticket open so we don't forget, but I think you can remove the "Critical" label.

**Comment by appukuttan-shailesh** [comment]
Has been implemented in Collab v2 web apps.
v1 apps will soon be dropped.
