### ISSUE TITLE
REST API for retrieving results doesn't show related files info

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#246]
Tests can have related files associated with the results. These are saved as part of the validation data.

Currently, when retrieving a test info, e.g. result UUID = "586297a7-ab7d-4099-843b-b0b7bc5f6670", we get:

```
{u'results': [{u'hash': None,
   u'id': u'586297a7-ab7d-4099-843b-b0b7bc5f6670',
   u'model_version_id': u'76a58395-126e-4998-9c6e-e3fbc494d1b4',
   u'normalized_score': 4.67996922253749,
   u'passed': None,
   u'platform': u"{'system_name': 'Linux', 'ip_addr': '127.0.0.1', 'architecture_bits': '64bit', 'machine': 'x86_64', 'architecture_linkage': 'ELF', 'version': '#169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019', 'release': '4.4.0-143-generic', 'network_name': 'ef552d2c4434', 'processor': ''}",
   u'project': u'54781',
   u'results_storage': u'collab://54781/validation_results/2019-06-11/CA1_Bianchi_2012_20190611-114234',
   u'runtime': None,
   u'score': 4.67996922253749,
   u'test_code_id': u'bacb333e-6b34-4940-9b06-d630b2efe016',
   u'timestamp': u'2019-06-11T11:42:56.453266Z'}]}
```

This lacks any info on the related files and their paths. Therefore these files and their paths are not accessible via the python client and the user is compelled to use the web app.

**Comment by apdavison** [comment]
In the KG version, the "results_storage" field contains a list of URIs (or a single URI if there's only one file).

**Comment by appukuttan-shailesh** [comment]
Yes, resolved. The URI is of the form (e.g.):
https://collab-storage-redirect.brainsimulation.eu/54781/validation_results/2019-06-25/Golding_et_al_2001_dichotomy_20190625-101317/figs_somaticfeat_UCL_data_Golding_2001_strong_prop_fig8B_absolute_features.pdf

with `https://collab-storage-redirect.brainsimulation.eu/` indicating that the file resides in Collab storage. The python client for the validation framework will be updated to accept these URL's and allow downloading of the files.

**Comment by appukuttan-shailesh** [comment]
NOTE: API updated as follow
"results_storage" key of result json is now a list of dicts; one dict per file

For files in Collab storage, dict will be of the form:
```
{
                "download_url": output_url,
                "collab_storage": {
                    "uuid": entity_uuid,
                    "path": entity_path
                }
}
```
e.g.
```
{u'collab_storage': {u'path': u'/54781/validation_results/2019-06-25/Poirazi_et_al_2003_CA1_multi_20190625-112220/figs_backpropagating_AP_Poirazi_et_al_2003_AP1_amp_means.pdf',
                     u'uuid': u'2183d8ba-fcd8-4f2d-9ff4-ced539a477c1'},
 u'download_url': u'https://collab.humanbrainproject.eu/#/collab/54781/nav/374631?state=uuid%3D2183d8ba-fcd8-4f2d-9ff4-ced539a477c1'}
```

If collab URL retrieval fails, then dict will have:
```
{
                "original_url": input_url
}
```
e.g. 
```
{u'original_url': u'https://collab-storage-redirect.brainsimulation.eu/54781/validation_results/2019-06-25/Golding_et_al_2001_dichotomy_20190625-101317/figs_somaticfeat_UCL_data_Golding_2001_strong_prop_fig8B_absolute_features.pdf'}
```

For files in other locations, dict format:
```
{
                "download_url": output_url
}
```
e.g. 
```
{u'download_url': u'https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/sp6_validation_data/HippoNetworkUnit/CA1_laminar_distribution_synapses.json'}
```
