### ISSUE TITLE
Allow model filter by author

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#247]
Previously we could filter the retrieved models such as:
`modelCatalog.list_models(author="Abcde")`

This is not possible currently in the KG (staging) environment.

**Comment by apdavison** [comment]
you can currently search by last name, e.g. `modelCatalog.list_models(author="Migliore")` Is that enough?

**Comment by appukuttan-shailesh** [comment]
Is it possible to have the input string be searched across both first names and last names?
Might offer a bit more flexibility.

For now even the above is good enough.
