### ISSUE TITLE
KG Results schema missing fields

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#250]
Results schema appears to be missing following fields:
- hash (used to compare duplicate results being stored because of re-uploading of same result files)
- runtime (time required for running test)

As summary:

Keys associated with old schema (production):
```
[u'hash',
 u'id',
 u'model_version_id',
 u'normalized_score',
 u'passed',
 u'platform',
 u'project',
 u'results_storage',
 u'runtime',
 u'score',
 u'test_code_id',
 u'timestamp']
```

Keys associated with results in KG (staging):
```
[u'id',
 u'model_version',
 u'model_version_id',
 u'normalized_score',
 u'old_uuid',
 u'passed',
 u'project',
 u'results_storage',
 u'score',
 u'test_code',
 u'test_code_id',
 u'timestamp',
 u'uri']
```

**Comment by apdavison** [comment]
can you point me to where the hash is calculated?

**Comment by appukuttan-shailesh** [comment]
Here:
https://github.com/HumanBrainProject/hbp-validation-client/blob/master/hbp_validation_framework/utils.py#L360

**Comment by appukuttan-shailesh** [comment]
Closing ticket as no longer relevant.
