### ISSUE TITLE
Different API outputs for different users

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#251]
Example:

`user = shailesh`
```
from hbp_validation_framework import ModelCatalog
modelCatalog = ModelCatalog(username="shailesh", environment="integration")
print len(modelCatalog.list_models(brain_region="hippocampus", collab_id="12027"))
```
**39**

`user = shailesha`
```
from hbp_validation_framework import ModelCatalog
modelCatalog = ModelCatalog(username="shailesha", environment="integration")
print len(modelCatalog.list_models(brain_region="hippocampus", collab_id="12027"))
```
**0**

Both users are part of "Team" in the Collab in context (12027)... even though this shouldn't be a factor for KG based backend I suppose where no access permissions can be set for read at such granularity.

**Comment by apdavison** [comment]
what do you get with `environment="production"`?

**Comment by appukuttan-shailesh** [comment]
With `environment="production"` I get **166** and **164** results respectively for the two accounts.

**Comment by apdavison** [comment]
Do those numbers include "e-models"?

**Comment by appukuttan-shailesh** [comment]
I believe not. A sample model on KG (from the 39) is:
CA1_pyr_cACpyr_oh140807_A0_idG_20190328143451
UUID: 055557a5-1bc6-4f7e-9816-981813596f9c

**Comment by apdavison** [comment]
hmm, well it looks as though integration fixes a bug in the current production. There are only 39 models associated with that collab, many of the models in the 166 have different collab_ids, which means that production isn't filtering the list of models properly.

I'm not sure why the `shailesha` account sees no models, my test account isn't even a member of that collab, but it gets 39 models (which is correct, as they are all public). The web server logs don't currently contain the username. I'll change that, then we should be able to figure out what is going wrong.

**Comment by appukuttan-shailesh** [comment]
This problem of not seeing any results first came up with Alex. He could see entries in his regular account, but not in his test account. I was subsequently able to reproduce this using my own test account.

**Comment by appukuttan-shailesh** [comment]
On the integration server, for user = `shailesh`
`print len(modelCatalog.list_models(brain_region="hippocampus"))`
returns **166**

But, user = `shailesha`
returns 0

**Comment by apdavison** [comment]
This seems to be an issue with Knowledge Graph permissions. Currently accounts that do not have SGA2 accreditation need to be individually white-listed.

**Comment by appukuttan-shailesh** [comment]
Closing issue as no longer relevant.
