### ISSUE TITLE
Score should probably allow None or null values

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#253]
Score currently requires a numeric quantity (float) as indicated by the error message below:

> Exception: {"score":["A valid number is required."],"normalized_score":["A valid number is required."]}

I think it should probably allow None or null values to indicate tests were attempted to be run on a model but failed. It might not be appropriate to simply throw an error for all such situations. 

For instance, inability of a cell to produce an AP for a specific level of stimulus and thereby no peak AP height being reported should be recorded as a "null", "NA" etc, to indicate that the test infact had been run on the model but didn't yield a result.

In the absence of this, as a workaround users have to resort to setting ~infinity values to indicate the same.

**Comment by apdavison** [comment]
What about using NaN?

**Comment by appukuttan-shailesh** [comment]
Even that works fine. We just need to ensure that a numeric value is not enforced (in the APIs, Python client etc) for scores to accomodate these scenarios.

**Comment by apdavison** [comment]
NaN is a numeric value

**Comment by appukuttan-shailesh** [comment]
True.... this can be closed.
