### ISSUE TITLE
Result related files not returned by API as intended

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#256]
Related to #246 
Expected output form for files on Collab storage is [indicated here](https://github.com/HumanBrainProject/hbp-validation-framework/issues/246#issuecomment-517194062).

Currently, REST API returns result related file info as:
> GET https://validation-staging.brainsimulation.eu/results/?order=&id=a19add16-5873-4b99-b043-5e020c7d6fb6
```
"results_storage": [
                {
                    "download_url": "collab://8123/validation_results/2019-10-25/CA1_pyr_cACpyr_oh140807_A0_idG_20170915113354_20191025-134432"
                }
```

The above resource is a directory on Collab storage containing 21 individual files. As per #246 , we should return a **list of 21 dicts**, each of the form:
```
{
                "download_url": output_url,
                "collab_storage": {
                    "uuid": entity_uuid,
                    "path": entity_path
                }
}
```
@apdavison : Any ideas why the API doesn't behave as expected, even though this was implemented in #246?

**Comment by apdavison** [comment]
All "collab://" URLs should have been replaced by "https://collab-storage-redirect.brainsimulation.eu/"-style URLs during the migration. Has the Python client been updated to also do this?

**Comment by appukuttan-shailesh** [comment]
No, the Python client hasn't yet been updated for the same. I have made the change now, but will make a PR after I have had a chance to test the related supporting functions (that helped translate these URLs). Could you let me know once the existing entries in the database have been fixed?

**Comment by apdavison** [comment]
I've fixed the first 10000, but there is a KG bug preventing me from changing the remaining 6000 or so. I've reported it, and I'll let you know when the remainder are fixed.

**Comment by appukuttan-shailesh** [comment]
Sure, thanks.

**Comment by apdavison** [comment]
When you have a collab folder containing related files, does the Python client save the URL of the folder, or of all the individual files?

**Comment by appukuttan-shailesh** [comment]
As per [this](https://github.com/appukuttan-shailesh/hbp-validation-client/blob/master/hbp_validation_framework/datastores.py#L142), [this](https://github.com/appukuttan-shailesh/hbp-validation-client/blob/master/hbp_validation_framework/__init__.py#L1363) and [this](https://github.com/appukuttan-shailesh/hbp-validation-client/blob/master/hbp_validation_framework/utils.py#L372), it simply saves the base directory URL.

**Comment by apdavison** [comment]
I think it would be better to modify the client to save each result file separately in the KG, rather than saving just the base directory URL.

**Comment by appukuttan-shailesh** [comment]
I am starting on saving related files separately on KG.

@apdavison : Were you able to update the remaing ~6000 result entries?

**Comment by appukuttan-shailesh** [comment]
Updated CollabDataStore upload method. Now allows for sub-directories as well as returning list of individual files (as desired).

https://github.com/appukuttan-shailesh/hbp-validation-client/commit/c616d7b999811e3247ca2a25e39050988a4cdeb5

**Comment by appukuttan-shailesh** [comment]
For reference:
with a v1 token we currently obtain output such as:
```
"results_storage": [
    {
        "collab_storage": {
            "path": "/69441/validation_results/2020-04-10/Hippocampus_CA1_Poirazi_model_with_STDP_mechanism_20200410-071403/traces.pdf",
            "uuid": "9f32eafc-8e5c-493c-983e-72c17c2e0995"
        },
        "download_url": "https://collab.humanbrainproject.eu/#/collab/69441/nav/471125?state=uuid%3D9f32eafc-8e5c-493c-983e-72c17c2e0995"
    },
    {
        "collab_storage": {
            "path": "/69441/validation_results/2020-04-10/Hippocampus_CA1_Poirazi_model_with_STDP_mechanism_20200410-071403/data.csv",
            "uuid": "2982a1eb-2d30-4b19-9f9d-015e9bdf8164"
        },
        "download_url": "https://collab.humanbrainproject.eu/#/collab/69441/nav/471125?state=uuid%3D2982a1eb-2d30-4b19-9f9d-015e9bdf8164"
    }
],
```

but with a Collab v2 token, we get:
```
"results_storage": [
    {
        "original_url": "https://collab-storage-redirect.brainsimulation.eu/69441/validation_results/2020-04-10/Hippocampus_CA1_Poirazi_model_with_STDP_mechanism_20200410-071403/traces.pdf"
    },
    {
        "original_url": "https://collab-storage-redirect.brainsimulation.eu/69441/validation_results/2020-04-10/Hippocampus_CA1_Poirazi_model_with_STDP_mechanism_20200410-071403/data.csv"
    }
],
```

**Reason:** 
Collaboratory v1 Storage uses the v1 token, a v2 token doesn’t let the server obtain the storage information. So file paths on v1 storage cannot be accessed via v2 token.

We will need to migrate all result related files on v1 storage to another appropriate location: CSCS storage or Collab v2 seafile storage.

**Comment by appukuttan-shailesh** [comment]
Closed as v2 APIs have been implemented with a slightly different format.
