### ISSUE TITLE
API calls blocked by CORS policy

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#267]
I get this for all calls to the APIs via the apps (works fine using dyamics docs and postman):

> Access to XMLHttpRequest at 'https://validation-v2.brainsimulation.eu/vocab/' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I referred to this:
https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141
and using `proxyurl = "https://cors-anywhere.herokuapp.com/";` for the time being to proceed with testing. (It works fine with the proxy url prefixed to the API call).

But we should enable it on the server later on, to avoid dependence on the proxy url.

**Comment by apdavison** [comment]
Implemented in 487207bf
