### ISSUE TITLE
Update naming of terms in API for Results

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#268]
Since we have renamed "codes" (under "tests") to "instances", I think for consistency we should also make this change under "results"...... rename "test_code_id" to "test_instance_id".

Also, "results" should also change "model_version_id" to "model_instance_id".

Currently, sample output of API (v2):
```
[
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "uri": "string",
    "old_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "model_version_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "test_code_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "results_storage": [
      "string"
    ],
    "score": 0,
    "passed": true,
    "timestamp": "2020-06-26T09:38:20.283Z",
    "project_id": "string",
    "normalized_score": 0
  }
]
```

So change:
`test_code_id` => `test_instance_id`
`model_version_id` => `model_instance_id`

**Comment by appukuttan-shailesh** [comment]
This will also require changes in the Python client.... e.g. utils.py (for score matrix etc)

**Comment by apdavison** [comment]
Implemented in #36dfcb58

Will you take care of the changes in the Python client?

**Comment by appukuttan-shailesh** [comment]
Ok :+1:

**Comment by appukuttan-shailesh** [comment]
https://github.com/HumanBrainProject/hbp-validation-client/issues/75
