### ISSUE TITLE
Rename 'status' field in tests to 'test_status'

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#272]
Controlled vocabularies currently output the following keys:
```
['brain_region', 'species', 'model_scope', 'cell_type', 'abstraction_level', 'recording_modality', 'test_type', 'score_type', 'test_status', 'license']
```

To remain consistent with naming of terms across APIs, we should rename `status` to `test_status` (similar to what we already do for `test_type`) in the below APIs: 

GET /tests/
PUT /tests/
POSTS /tests/

**Comment by appukuttan-shailesh** [comment]
@apdavison : A related query on this field 'status':

I tried to create a test:
POST https://validation-v2.brainsimulation.eu/tests/
Payload:
```
{name: "IGNORE - test test 1", alias: "Jane Doe",…}
alias: "Jane Doe"
author: [{given_name: "Jane", family_name: "Doe"}, {given_name: "John", family_name: "Doe"}]
brain_region: null
cell_type: null
data_location: "https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/sp6_validation_data/basalunit/YJ150915_c67D1ch01D2ch23-c6.zip"
data_type: "Mean, SD"
description: "some desc"
instances: [{version: "1.1", repository: "https://github.com/joffreygonin/hbp-validation-framework_dev",…}]
name: "IGNORE - test test 1"
recording_modality: null
score_type: null
species: null
status: null
test_type: null
```

Output:
>{"detail":[{"loc":["body","status"],"msg":"none is not an allowed value","type":"type_error.none.not_allowed"},{"loc":["body","data_location"],"msg":"value is not a valid list","type":"type_error.list"}]}

I understand the problem with 'data_location' (requiring to be input as list), but was wondering about 'status'. Is it intended that we have none/null disallowed for this field? Most of the other fields (e.g. brain_region, species, ...) accept this (as we had planned previously).

**Comment by apdavison** [comment]
I'm keen to maintain consistency across the API, but the problem is that the name "test_status" is redundant within the "tests" endpoints, so I prefer to keep "status". The "tests_" prefix is added in the "vocabs" endpoint simply because  "status" is ambiguous in that context.

I realize we have "test_type", but there the argument is that "type" (i) is ambiguous even given the context of the endpoint, and (ii) is a Python reserved name.

**Comment by apdavison** [comment]
The default value for "status" is "proposal". If your payload does not include the "status" key, this default should be applied.

(the API distinguishes between "field is missing" and "field is explicitly set to null")

**Comment by appukuttan-shailesh** [comment]
`status` has been renamed to `implementation_status` to maintain uniform naming across all APIs
See: https://github.com/apdavison/hbp-validation-framework/commit/873f2d63f92ac167b5ad271908de59648a4b88a0
