### ISSUE TITLE
Handling latex in model and test descriptions

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#276]
https://github.com/appukuttan-shailesh/hbp-validation-framework/commit/7c30628fcb35e57430463b336fd907bd8e5e0edd and https://github.com/appukuttan-shailesh/hbp-validation-framework/commit/1d1401b4ea257b6bed5312f1e61ea018245d7098 implement permitting latex math equations to be added to model and test description fields.

I have checked that we can now use markdown, html, and latex within these fields.

Sample entry with markdown and latex:
model_id = 0b46a720-5a60-4fbb-923a-80dfe2a4dc7a

Sample entry with markdown / HTML:
model_id = 01da73a6-8715-431b-aaa7-efcd9358c786

@apdavison : can you take a look and see if all is fine?

**Comment by apdavison** [comment]
yes, this looks good. I've deployed the changes, and the latex displays correctly.
