### ISSUE TITLE
v2 REST API performance issue

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#282]
The REST APIs for v2 of the validation framework is showing two types of issues recently:

1) The REST API calls fail frequently (increasingly so in recent days). The responses are frequently delayed (significantly, thereby affecting functionality), or simply fail. The very same request will then succeed on the next call immediately afterwards (while the initial request would still be in a pending state).

2) The server seems to raise CORS policy related problems spradically, and resolves with time on its own.

> Access to XMLHttpRequest at 'https://validation-v2.brainsimulation.eu/tests/?&size=1000000' from origin 'https://model-catalog.brainsimulation.eu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

These need to be investigated as they **significantly** affect the user experience of using the web apps.

**Comment by apdavison** [comment]
Note that the CORS error is a red-herring, I think, it's just that the 500 error responses don't contain CORS headers.

#309 should be a partial fix for the performance problems, to improve performance further we'll need server-side changes.
