### ISSUE TITLE
API end-point for licenses 

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#293]
Regarding:
https://validation-v2.brainsimulation.eu/docs#/Controlled%20vocabularies/list_licenses_vocab_license__get

The filter seems to have two valid values:
- all (default)
- popular

Choosing `all` only returns:
`
[
  "GNU General Public License 2 or later",
  "CeCILL v2"
]
`

These values seem to be fetched from fairgraph; see [here](https://github.com/HumanBrainProject/hbp-validation-framework/blob/2ba3da37c9f237dc7d2f43600aac0ae07f08cdf9/validation_service_v2/validation_service/resources/vocab.py#L99) and [here](https://github.com/HumanBrainProject/hbp-validation-framework/blob/2ba3da37c9f237dc7d2f43600aac0ae07f08cdf9/validation_service_v2/validation_service/data_models.py#L126).

while `popular` returns:
`
[
  "Apache License 2.0",
  "BSD 2-Clause \"Simplified\" License",
  "BSD 3-Clause \"New\" or \"Revised\" License",
  "Creative Commons Attribution 4.0 International",
  "Creative Commons Attribution Non Commercial 4.0 International",
  "Creative Commons Attribution Share Alike 4.0 International",
  "Creative Commons Zero v1.0 Universal",
  "GNU General Public License v2.0 or later",
  "GNU General Public License v3.0 or later",
  "GNU Lesser General Public License v3.0 or later",
  "MIT License"
]
`

These values are hard-coded [here](https://github.com/HumanBrainProject/hbp-validation-framework/blob/2ba3da37c9f237dc7d2f43600aac0ae07f08cdf9/validation_service_v2/validation_service/resources/vocab.py#L75).

I believe `popular` should return a sub-set of `all`. Isn't that the expected behavior @apdavison ?

**Comment by apdavison** [comment]
yes. 'all' is supposed to use the list pulled from "https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json" but I had to disable it because it was causing problems with server startup. I need to revisit this.

**Comment by apdavison** [comment]
Fixed in f2f0f800
