### ISSUE TITLE
Swagger docs not working as expected for few cases

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#320]
E.g. 
https://validation-v2.brainsimulation.eu/docs#/Validation%20Results/query_results_summary_results_summary__get

Setting model_id = 01006de7-e861-45fb-abf4-3c84e609d33b

Resultant request URL (auto generated):
https://validation-v2.brainsimulation.eu/results-summary/?model_id=01006de7-e861-45fb-abf4-3c84e609d33b&size=100&from_index=0

Also tried removing last parameter (setting `from_index` to empty string):
https://validation-v2.brainsimulation.eu/results-summary/?model_id=01006de7-e861-45fb-abf4-3c84e609d33b&size=100

**Output:**
Code: undocumented
Details: TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

@apdavison : any idea what's wrong?

Works fine from within app. E.g.
https://validation-v2.brainsimulation.eu/results-summary/?model_id=01006de7-e861-45fb-abf4-3c84e609d33b&size=1000000

**Comment by apdavison** [comment]
This currently works with https://validation.brainsimulation.eu/docs#/Validation%20Results/query_results_summary_results_summary__get
