### ISSUE TITLE
Whether Models 'organization' data should be restricted to specific values

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#85]
@HFragnaud :
Adding a new model with 'organization' parameter via the python client.

If parameter = "", then model gets accepted and is listed on the model catalog.
e.g. "Test Model - B11"

If parameter = "UNIC-SP6", then model gets accepted BUT IS NOT listed on the model catalog.
e.g. "Test Model - B14"

In both cases, I get a proper UUID of the model that has been added. So what could be the problem here?

**Comment by appukuttan-shailesh** [comment]
Update: 
@HFragnaud:  informed me that the organization field has specific valid values, e.g. "HBP-SP6".

@apdavison: I suppose we need to discuss if this should be so, or should we allow the user to enter any value. I thought we had decided on the latter on slack.

(Changing the post title appropriately).

**Comment by appukuttan-shailesh** [comment]
@HFragnaud : One problem following from the original post here is that, even when the user enters an "Invalid" value for `organization`, the model is still getting added to the database and a `UUID` is being returned.

This needs to be corrected to ensure that the model is not registered in the database if any paramater values are incorrect.

**Comment by apdavison** [comment]
> should we allow the user to enter any value

Ideally there should be a drop-down list with existing values, but also the option of adding a new value. For now, we could just have the drop-down list and ask people to contact us if they want a new value added.

**Comment by appukuttan-shailesh** [comment]
Issue is stale and likely irrelevant to new version of API and docs.
